version: "3"

services:
  postgres:
    image: "postgres:11"
    container_name: "realworld_postgres"
    ports:
      - "54320:5432"
    volumes:
      - ./.docker/data:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=userpassword
    networks:
      - drash-app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  drash:
    container_name: realworld_drash
    image: tjozsa/conduit
    volumes:
      - ./src:/var/www/src
    working_dir: /var/www/src
    ports:
      - "1667:1667"
    networks:
      - drash-app-network
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      # exit code must be 0 or 1
      #test: curl --fail http://drash:1667/ || exit 1
      # test returnd page's content length
      test: curl -sD - -o /dev/null http://localhost:1667/ | grep 'content-length' | cut -d\  -f2 | tr -d '\r' | xargs -I % test % -eq 1186 || exit 1
      interval: 10s
      timeout: 10s
      retries: 8
      start_period: 10s


networks:
  drash-app-network:
    driver: bridge
