name: selenium-tests
on:
  push:
    branches:
      - actions-setup
      - master
    pull_requests:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - 3.10.4
    steps:
      - uses: actions/checkout@v2

      - run: docker compose up -d

      - name: Sleep until conduit starts
        run: sleep 60
        shell: bash

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install software
        run: sudo apt-get install -y chromium-browser

      - name: Install the necessary packages
        run: pip install webdriver-manager selenium==3.141.0 pytest

      - name: Run the PytTest script
        run: pytest
