name: selenium-tests
on:
  push:
    branches-ignore:
      - 'gh-pages'
      - 'tweak-pytest'

jobs:
  conduit-selenium-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out local repository
        uses: actions/checkout@v3

      # start conduip app services, and wait for then to become healthy
      - name: Start conduit app
        run: docker compose up --wait

      # include other steps to give conduit container time to start
      - name: Get Allure history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Install poetry
        run: pipx install poetry
        
      - name: Set up Python 3.10.4
        uses: actions/setup-python@v3
        with:
          python-version: 3.10.4
          cache: 'poetry'

      - name: Install the necessary packages
        run: poetry install

      - name: Run the PytTest script
        run: poetry run pytest

      - name: Allure Report action from marketplace
        uses: simple-elf/allure-report-action@master
        if: always()
        #id: allure-report
        with:
          allure_results: allure-results
          #gh_pages: gh-pages
          #allure_report: allure-report
          allure_history: allure-history
          keep_reports: 20

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history
